PROJECT_ID: 'amic'
PROJECT_NAME: 'pam_in_chemnitz'
RECORDER_GROUP: 39
SPECIES_DATA: amic
DEPLOYMENT_LAT: 50.832
DEPLOYMENT_LON: 12.924
TIMEZONE: 'Europe/Berlin'
TIME_FORMAT: '24h'
DATE_FORMAT: '%d.%m.%Y'
DEFAULT_SITE_LOCALE: 'de'
RECORDERS:
  1: {id: '0271', lat: 50.850533, lon: 12.890730, habitat: 'habitat_urban', img: 'amic_unit_1.jpg'}
  2: {id: '0829', lat: 50.850231, lon: 12.890473, habitat: 'habitat_urban', img: 'amic_unit_2.jpg'}
  3: {id: '0269', lat: 50.850022, lon: 12.890146, habitat: 'habitat_urban', img: 'amic_unit_3.jpg'}
  4: {id: '0270', lat: 50.849055, lon: 12.889994, habitat: 'habitat_forest', img: 'amic_unit_4.jpg'}
MAP_ZOOM_LEVEL: 17
MAIN_HEADER_IMG_LIST: ['amic_main_header_1.jpg']
ABOUT_HEADER_IMG_LIST: ['amic_about_header_1.jpg']
LIVE_STREAM_URL: ''
DONATION_URL: ''
PROJECT_ACRONYM: 'AMiC'
PRIMARY_COLOR: '#385B75'
SECONDARY_COLOR: '#2c3b47'
PLOT_PRIMARY_COLOR: '#385B75'
BUTTON_COLOR: '#385B75'
FAVICON: 'amic_favicon.ico'
PAGE_TITLE: 'AMiC'
LOGO_MOBILE: 'amic_logo_short.png'
LOGO_DESKTOP: 'amic_logo_short.png'
LEARN_MORE_BASE_URL: 'https://ebird.org/species/'
FOOTER_LINKS:
  widget_footer_link_section_site:
    - {name: "widget_footer_site_links_home", href: "/"}
    - {name: "widget_footer_site_links_detections", href: "/detections"}
    - {name: "widget_footer_site_links_recording_units", href: "/recorder/1"}
    - {name: "widget_footer_site_links_about_the_project", href: "/about"}
    - {name: "widget_footer_site_links_contact", href: "/about#about-contact"}
  widget_footer_link_section_botanical_garden:
    - {name: "widget_footer_botanical_garden_chemnitz_about", href: "https://www.chemnitz.de/en/living-in-chemnitz/leisure-time/botanical-garden", target: "_blank"}
    - {name: "widget_footer_botanical_garden_chemnitz_history", href: "https://www.chemnitz.de/en/living-in-chemnitz/leisure-time/botanical-garden/history", target: "_blank"}
    - {name: "widget_footer_botanical_garden_chemnitz_school_biology_center", href: "https://www.chemnitz.de/en/living-in-chemnitz/leisure-time/botanical-garden/school-biology-centre", target: "_blank"}
    - {name: "widget_footer_botanical_garden_chemnitz_park_map", href: "https://d2vw8mc5mcb3gm.cloudfront.net/fileadmin/chemnitz/media/leben-in-chemnitz/freizeit/botanischer_garten/botanischer_garten_parkplan.pdf", target: "_blank"}
  widget_footer_link_section_oekofor:
    - {name: "widget_footer_oekofor_about_us", href: "https://www.oekofor.de/en/#about", target: "_blank"}
    - {name: "widget_footer_oekofor_services", href: "https://www.oekofor.de/en/#services", target: "_blank"}
    - {name: "widget_footer_oekofor_ecopi", href: "https://www.oekofor.de/en/portfolio/erfassungstechnik_en/", target: "_blank"}
    - {name: "widget_footer_oekofor_contact", href: "https://www.oekofor.de/en/#contact", target: "_blank"}
  widget_footer_link_section_yang_center:
    - {name: "widget_footer_yang_center_our_values", href: "https://www.birds.cornell.edu/ccb/our-values/", target: "_blank"}
    - {name: "widget_footer_yang_center_research", href: "https://www.birds.cornell.edu/ccb/research/", target: "_blank"}
    - {name: "widget_footer_yang_center_technology", href: "https://www.birds.cornell.edu/ccb/technology/", target: "_blank"}
    - {name: "widget_footer_yang_center_education", href: "https://www.birds.cornell.edu/ccb/education/", target: "_blank"}
    - {name: "widget_footer_yang_center_publications", href: "https://www.birds.cornell.edu/ccb/publications/", target: "_blank"}
  widget_footer_link_section_tuc:
    - {name: "widget_footer_tu_chemnitz_university", href: "https://www.tu-chemnitz.de/index.html.en", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_degree_programs", href: "https://www.tu-chemnitz.de/studierendenservice/zsb/studiengaenge/en/", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_international_office", href: "https://www.tu-chemnitz.de/international/index.php.en", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_research", href: "https://www.tu-chemnitz.de/forschung/index.php.en", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_computer_science", href: "https://www.tu-chemnitz.de/informatik/index.php.en", target: "_blank"}
  widget_footer_link_section_about:
    - {name: "widget_footer_about_web_accessibility_assistance", href: "https://www.birds.cornell.edu/home/web-accessibility-assistance/", target: "_blank"}
    - {name: "widget_footer_about_privacy_policy", href: "https://privacy.cornell.edu/information-use-cornell", target: "_blank"}
    - {name: "widget_footer_about_terms_of_use", href: "https://www.birds.cornell.edu/home/terms-of-use/", target: "_blank"}
COPYRIGHT_HOLDERS: ""
FOOTER_TOP_LOGO: 'birdnet_logo_white.png'
FOOTER_BOTTOM_LOGOS: ['oekofor_logo_white.png', 'yang_logo_white.png', 'tuc_logo_white.png']
TEAM_MEMBERS:
  - {name: "Stefan Kahl", role: "about_team_role_project_lead_and_web", img: "stefan.png"}
  - {name: "Felix Günther", role: "about_team_role_backend", img: "felix.png"}
  - {name: "Raja Seifert", role: "about_team_role_design", img: "raja.png"}
  - {name: "Max Mauermann", role: "about_team_role_web", img: "max.png"}
  - {name: "Josef Haupt", role: "about_team_role_web", img: "josef.png"}