PROJECT_ID: 'amic'
PROJECT_NAME: 'pam_in_chemnitz'
RECORDER_GROUP: 39
SPECIES_DATA: amic
DEPLOYMENT_LAT: 50.832
DEPLOYMENT_LON: 12.924
TIMEZONE: 'Europe/Berlin'
TIME_FORMAT: '24h'
RECORDERS:
  1: {id: '0271', lat: 50.850533, lon: 12.890730, habitat: 'habitat_urban', img: 'amic_unit_1.jpg'}
  2: {id: '0829', lat: 50.850231, lon: 12.890473, habitat: 'habitat_urban', img: 'amic_unit_2.jpg'}
  3: {id: '0269', lat: 50.850022, lon: 12.890146, habitat: 'habitat_urban', img: 'amic_unit_3.jpg'}
  4: {id: '0270', lat: 50.849055, lon: 12.889994, habitat: 'habitat_forest', img: 'amic_unit_4.jpg'}
MAP_ZOOM_LEVEL: 17
MAIN_HEADER_IMG_LIST: ['amic_main_header_1.jpg']
ABOUT_HEADER_IMG_LIST: ['amic_about_header_1.jpg']
LIVE_STREAM_URL: ''
DONATION_URL: ''
PROJECT_ACRONYM: 'AMiC'
PROJECT_SUBTITLE: 'AI-powered acoustic monitoring'
PROJECT_SUBTITLE_DESC: 'We listen to the sounds of birds and investigate how traffic noise impacts their natural behavior.'
PROJECT_GOAL: 'The Acoustic Monitoring in Chemnitz project combines technology and community engagement to showcase the power of acoustic monitoring in understanding the natural world. By listening to the sounds of the birds in the Botanical Garden, visitors can explore how advanced tools are used to study wildlife and gain a deeper appreciation for the diversity of birdlife in the area.'
PRIMARY_COLOR: '#385B75'
SECONDARY_COLOR: '#2c3b47'
PLOT_PRIMARY_COLOR: '#385B75'
BUTTON_COLOR: '#385B75'
FAVICON: 'amic_favicon.ico'
PAGE_TITLE: 'AMiC'
LOGO_MOBILE: 'amic_logo_short.png'
LOGO_DESKTOP: 'amic_logo_wide.png'
LEARN_MORE_BASE_URL: 'https://ebird.org/species/'
FOOTER_LINKS:
  Site Links:
    - {name: "Home", href: "/"}
    - {name: "Detections", href: "/detections"}
    - {name: "Recording units", href: "/recorder/1"}
    - {name: "About the project", href: "/about"}
    - {name: "Contact", href: "/about#about-contact"}
  Botanical Garden Chemnitz:
    - {name: "About", href: "https://www.chemnitz.de/en/living-in-chemnitz/leisure-time/botanical-garden", target: "_blank"}
    - {name: "History", href: "https://www.chemnitz.de/en/living-in-chemnitz/leisure-time/botanical-garden/history", target: "_blank"}
    - {name: "School Biology Center", href: "https://www.chemnitz.de/en/living-in-chemnitz/leisure-time/botanical-garden/school-biology-centre", target: "_blank"}
    - {name: "Park Map", href: "https://d2vw8mc5mcb3gm.cloudfront.net/fileadmin/chemnitz/media/leben-in-chemnitz/freizeit/botanischer_garten/botanischer_garten_parkplan.pdf", target: "_blank"}
  OekoFor:
    - {name: "About us", href: "https://www.oekofor.de/en/#about", target: "_blank"}
    - {name: "Services", href: "https://www.oekofor.de/en/#services", target: "_blank"}
    - {name: "ecoPi", href: "https://www.oekofor.de/en/portfolio/erfassungstechnik_en/", target: "_blank"}
    - {name: "Contact", href: "https://www.oekofor.de/en/#contact", target: "_blank"}
  Yang Center:
    - {name: "Our values", href: "https://www.birds.cornell.edu/ccb/our-values/", target: "_blank"}
    - {name: "Research", href: "https://www.birds.cornell.edu/ccb/research/", target: "_blank"}
    - {name: "Technology", href: "https://www.birds.cornell.edu/ccb/technology/", target: "_blank"}
    - {name: "Education", href: "https://www.birds.cornell.edu/ccb/education/", target: "_blank"}
    - {name: "Publications", href: "https://www.birds.cornell.edu/ccb/publications/", target: "_blank"}
  TU Chemnitz:
    - {name: "University", href: "https://www.tu-chemnitz.de/index.html.en", target: "_blank"}
    - {name: "Degree programs", href: "https://www.tu-chemnitz.de/studierendenservice/zsb/studiengaenge/en/", target: "_blank"}
    - {name: "International Office", href: "https://www.tu-chemnitz.de/international/index.php.en", target: "_blank"}
    - {name: "Research", href: "https://www.tu-chemnitz.de/forschung/index.php.en", target: "_blank"}
    - {name: "Computer Science", href: "https://www.tu-chemnitz.de/informatik/index.php.en", target: "_blank"}
  About:
    - {name: "Legal Notice", href: "https://www.tu-chemnitz.de/tu/impressum.html", target: "_blank"}
    - {name: "Privacy Policy", href: "https://www.tu-chemnitz.de/tu/datenschutz.html", target: "_blank"}
    - {name: "Accessibility", href: "https://www.tu-chemnitz.de/tu/barrierefreiheit.html", target: "_blank"}
COPYRIGHT_HOLDERS: ""
FOOTER_TOP_LOGO: 'birdnet_logo_white.png'
FOOTER_BOTTOM_LOGOS: ['oekofor_logo_white.png', 'yang_logo_white.png', 'tuc_logo_white.png']
TEAM_MEMBERS:
  - {name: "Stefan Kahl", role: "Project lead and web development", img: "stefan.png"}
  - {name: "Felix Günther", role: "Backend development", img: "felix.png"}
  - {name: "Raja Seifert", role: "Visual design", img: "raja.png"}
  - {name: "Max Mauermann", role: "Web development", img: "max.png"}
  - {name: "Josef Haupt", role: "Web development", img: "josef.png"}