PROJECT_ID: 'neeri'
PROJECT_NAME: '017_neerach_ried'
RECORDER_GROUP: 45
SPECIES_DATA: neeracherried
DEPLOYMENT_LAT: 47.500
DEPLOYMENT_LON: 8.4790
TIMEZONE: 'Europe/Berlin'
TIME_FORMAT: '24h'
DATE_FORMAT: '%d/%m/%Y'
RECORDERS:
  1: {id: '0357', lat: 47.50141, lon: 8.48344, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  2: {id: '0368', lat: 47.50364, lon: 8.483333, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  3: {id: '0518', lat: 47.50269, lon: 8.48399, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  4: {id: '0517', lat: 47.50026, lon: 8.48248, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  5: {id: '0525', lat: 47.50249, lon: 8.48239, habitat: 'habitat_raised_bog', img: 'neeri_unit_5.jpg'}
  6: {id: '0523', lat: 47.50016, lon: 8.48449, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  7: {id: '0516', lat: 47.50095, lon: 8.48666, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  8: {id: '0513', lat: 47.50006, lon: 8.48592, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  9: {id: '0358', lat: 47.50255, lon: 8.48767, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  10: {id: '0526', lat: 47.50372, lon: 8.48661, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  11: {id: '0524', lat: 47.50464, lon: 8.48788, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
  12: {id: '0378', lat: 47.503143, lon: 8.488629, habitat: 'habitat_raised_bog', img: 'dummy_recorder.jpg'}
MAP_ZOOM_LEVEL: 16
MAIN_HEADER_IMG_LIST: ['neeri_main_header_1.jpg']
ABOUT_HEADER_IMG_LIST: ['neeri_about_header_1.jpg']
LIVE_STREAM_URL: ''
DONATION_URL: 'https://www.birdlife.ch/en/content/donations'
PROJECT_ACRONYM: 'BirdLife'
PRIMARY_COLOR: '#6cae3d'
SECONDARY_COLOR: '#3b6da8'
PLOT_PRIMARY_COLOR: '#486f9c'
BUTTON_COLOR: '#6cae3d'
FAVICON: 'neeri_favicon.ico'
PAGE_TITLE: 'BirdLife Neeracherried'
LOGO_MOBILE: 'birdlife_ch_logo_bird.png'
LOGO_DESKTOP: 'birdlife_ch_logo_bird.png'
LEARN_MORE_BASE_URL: 'https://ebird.org/species/'
FOOTER_LINKS:
  widget_footer_link_section_site:
    - {name: "widget_footer_site_links_home", href: "/"}
    - {name: "widget_footer_site_links_detections", href: "/detections"}
    - {name: "widget_footer_site_links_recording_units", href: "/recorder/1"}
    - {name: "widget_footer_site_links_about_the_project", href: "/about"}
    - {name: "widget_footer_site_links_contact", href: "/about#about-contact"}
  widget_footer_link_section_birdlife:
    - {name: "widget_footer_birdlife_projects", href: "https://www.birdlife.org/projects/", target: "_blank"}
    - {name: "widget_footer_birdlife_visitor_centers", href: "https://www.birdlife.org/visitor-centers/", target: "_blank"}
    - {name: "widget_footer_birdlife_membership", href: "https://www.birdlife.org/membership/", target: "_blank"}
    - {name: "widget_footer_birdlife_support_our_work", href: "https://www.birdlife.org/support-our-work/", target: "_blank"}
  widget_footer_link_section_oekofor:
    - {name: "widget_footer_oekofor_about_us", href: "https://www.oekofor.de/en/#about", target: "_blank"}
    - {name: "widget_footer_oekofor_services", href: "https://www.oekofor.de/en/#services", target: "_blank"}
    - {name: "widget_footer_oekofor_ecopi", href: "https://www.oekofor.de/en/portfolio/erfassungstechnik_en/", target: "_blank"}
    - {name: "widget_footer_oekofor_contact", href: "https://www.oekofor.de/en/#contact", target: "_blank"}
  widget_footer_link_section_yang_center:
    - {name: "widget_footer_yang_center_our_values", href: "https://www.birds.cornell.edu/ccb/our-values/", target: "_blank"}
    - {name: "widget_footer_yang_center_research", href: "https://www.birds.cornell.edu/ccb/research/", target: "_blank"}
    - {name: "widget_footer_yang_center_technology", href: "https://www.birds.cornell.edu/ccb/technology/", target: "_blank"}
    - {name: "widget_footer_yang_center_education", href: "https://www.birds.cornell.edu/ccb/education/", target: "_blank"}
    - {name: "widget_footer_yang_center_publications", href: "https://www.birds.cornell.edu/ccb/publications/", target: "_blank"}
  widget_footer_link_section_tuc:
    - {name: "widget_footer_tu_chemnitz_university", href: "https://www.tu-chemnitz.de/index.html.en", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_degree_programs", href: "https://www.tu-chemnitz.de/studierendenservice/zsb/studiengaenge/en/", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_international_office", href: "https://www.tu-chemnitz.de/international/index.php.en", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_research", href: "https://www.tu-chemnitz.de/forschung/index.php.en", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_computer_science", href: "https://www.tu-chemnitz.de/informatik/index.php.en", target: "_blank"}
  widget_footer_link_section_about:
    - {name: "widget_footer_about_web_accessibility_assistance", href: "https://www.birds.cornell.edu/home/web-accessibility-assistance/", target: "_blank"}
    - {name: "widget_footer_about_privacy_policy", href: "https://privacy.cornell.edu/information-use-cornell", target: "_blank"}
    - {name: "widget_footer_about_terms_of_use", href: "https://www.birds.cornell.edu/home/terms-of-use/", target: "_blank"}
COPYRIGHT_HOLDERS: ""
FOOTER_TOP_LOGO: 'birdnet_logo_white.png'
FOOTER_BOTTOM_LOGOS: ['birdlife_ch_logo_white.png', 'oekofor_logo_white.png', 'yang_logo_white.png', 'tuc_logo_white.png']
TEAM_MEMBERS:
  - {name: "Hendrik Reers", role: "about_team_role_project_lead", img: "hendrik.png"}
  - {name: "Stefan Kahl", role: "about_team_role_web", img: "stefan.png"}
  - {name: "Felix Günther", role: "about_team_role_backend", img: "felix.png"}
  - {name: "Max Mauermann", role: "about_team_role_web", img: "max.png"}
  - {name: "Josef Haupt", role: "about_team_role_web", img: "josef.png"}