PROJECT_ID: 'sustainscapes'
PROJECT_NAME: '101_sustain_scapes'
PROJECT_START_DATE: '20-06-2024' # dd-mm-yyyy
RECORDER_GROUP: 142
SPECIES_DATA: sustainscapes
DEPLOYMENT_LAT: 55.617
DEPLOYMENT_LON: 11.356
TIMEZONE: 'Europe/Copenhagen'
TIME_FORMAT: '24h'
DATE_FORMAT: '%d.%m.%Y'
DEFAULT_SITE_LOCALE: 'dk'
RECORDERS:
  2: {id: '0051', lat: 55.63533, lon: 11.35766, habitat: 'habitat_wetland_forest_inside', img: 'ss_unit_2.jpg', tooltip: 'right'}
  3: {id: '0052', lat: 55.63024, lon: 11.34016, habitat: 'habitat_wetland_open_inside', img: 'ss_unit_3.jpg', tooltip: 'right'}
  4: {id: '0053', lat: 55.62815, lon: 11.33319, habitat: 'habitat_wetland_open_edge', img: 'ss_unit_4.jpg', tooltip: 'left'}
  5: {id: '0054', lat: 55.61028, lon: 11.35812, habitat: 'habitat_wetland_forest_edge', img: 'ss_unit_5.jpg', tooltip: 'right'}
  6: {id: '0055', lat: 55.60057, lon: 11.37605, habitat: 'habitat_wetland_open_edge', img: 'ss_unit_6.jpg', tooltip: 'right'}
  7: {id: '0056', lat: 55.59943, lon: 11.37243, habitat: 'habitat_wetland_open_inside', img: 'ss_unit_7.jpg', tooltip: 'left'}
MAP_ZOOM_LEVEL: 13
MAIN_HEADER_IMG_LIST: ['ss_main_header_1.jpg', 'ss_main_header_2.jpg']
ABOUT_HEADER_IMG_LIST: ['ss_about_header_1.jpg']
LIVE_STREAM_URL: ''
DONATION_URL: ''
PROJECT_ACRONYM: 'SustainScapes'
PRIMARY_COLOR: '#3F7E44'
SECONDARY_COLOR: '#BFBB2E'
PLOT_PRIMARY_COLOR: '#3F7E44'
BUTTON_COLOR: '#3F7E44'
FAVICON: 'sustainscapes_favicon.ico'
PAGE_TITLE: 'SustainScapes'
LOGO_MOBILE: 'sustainscapes_logo_icon.png'
LOGO_DESKTOP: 'sustainscapes_logo_long.png'
LEARN_MORE_BASE_URL: 'https://ebird.org/species/'
FOOTER_LINKS:
  widget_footer_link_section_site:
    - {name: "widget_footer_site_links_home", href: "/"}
    - {name: "widget_footer_site_links_detections", href: "/detections"}
    - {name: "widget_footer_site_links_recording_units", href: "/recorder/2"}
    - {name: "widget_footer_site_links_about_the_project", href: "/about"}
    - {name: "widget_footer_site_links_contact", href: "/about#about-contact"}
  widget_footer_link_section_sustainscapes:
    - {name: "widget_footer_sustainscapes_link_1", href: "#", target: "_blank"}
    - {name: "widget_footer_sustainscapes_link_2", href: "#", target: "_blank"}
    - {name: "widget_footer_sustainscapes_link_3", href: "#", target: "_blank"}
  widget_footer_link_section_oekofor:
    - {name: "widget_footer_oekofor_about_us", href: "https://www.oekofor.de/en/#about", target: "_blank"}
    - {name: "widget_footer_oekofor_services", href: "https://www.oekofor.de/en/#services", target: "_blank"}
    - {name: "widget_footer_oekofor_ecopi", href: "https://www.oekofor.de/en/portfolio/erfassungstechnik_en/", target: "_blank"}
    - {name: "widget_footer_oekofor_contact", href: "https://www.oekofor.de/en/#contact", target: "_blank"}
  widget_footer_link_section_yang_center:
    - {name: "widget_footer_yang_center_home", href: "https://www.birds.cornell.edu/ccb/", target: "_blank"}
    - {name: "widget_footer_yang_center_research", href: "https://www.birds.cornell.edu/ccb/research/", target: "_blank"}
    - {name: "widget_footer_yang_center_technology", href: "https://www.birds.cornell.edu/ccb/technology/", target: "_blank"}
    - {name: "widget_footer_yang_center_education", href: "https://www.birds.cornell.edu/ccb/education/", target: "_blank"}
    - {name: "widget_footer_yang_center_publications", href: "https://www.birds.cornell.edu/ccb/publications/", target: "_blank"}
  widget_footer_link_section_tuc:
    - {name: "widget_footer_tu_chemnitz_university", href: "https://www.tu-chemnitz.de/index.html.en", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_degree_programs", href: "https://www.tu-chemnitz.de/studierendenservice/zsb/studiengaenge/en/", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_international_office", href: "https://www.tu-chemnitz.de/international/index.php.en", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_research", href: "https://www.tu-chemnitz.de/forschung/index.php.en", target: "_blank"}
    - {name: "widget_footer_tu_chemnitz_computer_science", href: "https://www.tu-chemnitz.de/informatik/index.php.en", target: "_blank"}
  widget_footer_link_section_about:
    - {name: "widget_footer_site_links_about_the_project", href: "/about"}
    - {name: "widget_footer_about_imprint", href: "/privacy"}
    - {name: "widget_footer_about_privacy_policy", href: "/privacy"}
COPYRIGHT_HOLDERS: ""
PARTNER_STATEMENT: "about_partnership_sustainscapes"
PARTNER_LOGOS: ['logo_box_lab.png', 'logo_box_tuc.png', 'logo_box_oekofor.png']
FOOTER_TOP_LOGO: 'birdnet_logo_white.png'
FOOTER_BOTTOM_LOGOS: ['oekofor_logo_white.png', 'yang_logo_white.png', 'tuc_logo_white.png']
TEAM_MEMBERS:
  - {name: "Stefan Kahl", role: "about_team_role_project_lead_and_web", img: "stefan.png"}
  - {name: "Felix Günther", role: "about_team_role_backend", img: "felix.png"}
  - {name: "Raja Seifert", role: "about_team_role_design", img: "raja.png"}
  - {name: "Max Mauermann", role: "about_team_role_web", img: "max.png"}
  - {name: "Josef Haupt", role: "about_team_role_web", img: "josef.png"}
PWA_MANIFEST: 'assets/sustainscapes_manifest.json'