PROJECT_ID: 'swamp'
PROJECT_NAME: '099_swamp'
RECORDER_GROUP: 99
SPECIES_DATA: 'swamp'
DEPLOYMENT_LAT: 42.479723
DEPLOYMENT_LON: -76.451566
TIMEZONE: 'America/New_York'
TIME_FORMAT: '12h'
DATE_FORMAT: '%m/%d/%Y'
RECORDERS:
  1: {id: '0271', lat: 42.4786, lon: -76.4407, habitat: 'habitat_shrubs_and_trees', img: 'swamp_unit_1.jpg'}
  2: {id: '0829', lat: 42.4768, lon: -76.4396, habitat: 'habitat_shrubs_and_meadow', img: 'swamp_unit_2.jpg'}
  3: {id: '0269', lat: 42.4769, lon: -76.4426, habitat: 'habitat_shrubs_and_meadow', img: 'swamp_unit_3.jpg'}
  4: {id: '0270', lat: 42.4769, lon: -76.4442, habitat: 'habitat_shrubs_and_trees', img: 'swamp_unit_4.jpg'}
  5: {id: '0272', lat: 42.4796, lon: -76.4514, habitat: 'habitat_feeder_garden_and_pond', img: 'swamp_unit_5.jpg'}
  7: {id: '0275', lat: 42.4801, lon: -76.4543, habitat: 'habitat_trees_and_pond', img: 'swamp_unit_7.jpg'}
  8: {id: '0276', lat: 42.4782, lon: -76.4547, habitat: 'habitat_forest', img: 'swamp_unit_8.jpg'}
  9: {id: '0274', lat: 42.4753, lon: -76.4451, habitat: 'habitat_forest_clearing', img: 'swamp_unit_9.jpg'}
  10: {id: '0277', lat: 42.4742, lon: -76.4488, habitat: 'habitat_shrubs_and_pond', img: 'swamp_unit_10.jpg'}
MAP_ZOOM_LEVEL: 15
MAIN_HEADER_IMG_LIST: ['ssw_main_header_1.jpg', 'ssw_main_header_2.jpg']
ABOUT_HEADER_IMG_LIST: ['ssw_about_header_1.jpg', 'ssw_about_header_2.jpg', 'ssw_about_header_3.jpg', 'ssw_about_header_4.jpg', 'ssw_about_header_5.jpg']
LIVE_STREAM_URL: 'https://birdnetlive.duckdns.org/ssw'
DONATION_URL: 'https://give.birds.cornell.edu/page/132162/donate/1?ea.tracking.id=ENR'
PROJECT_ACRONYM: 'SWAMP'
PRIMARY_COLOR: '#b31b1b'
SECONDARY_COLOR: '#2e261f'
PLOT_PRIMARY_COLOR: '#385B75'
BUTTON_COLOR: '#36824b'
FAVICON: 'swamp_favicon.ico'
PAGE_TITLE: 'SWAMP'
LOGO_MOBILE: 'clo_swamp_short_mobile_horizontal_color.png'
LOGO_DESKTOP: 'clo_swamp_short_horizontal_color.png'
LEARN_MORE_BASE_URL: 'https://www.allaboutbirds.org/guide/'
FOOTER_LINKS:
  widget_footer_link_section_site:
    - {name: "widget_footer_site_links_home", href: "/"}
    - {name: "widget_footer_site_links_detections", href: "/detections"}
    - {name: "widget_footer_site_links_recording_units", href: "/recorder/1"}
    - {name: "widget_footer_site_links_about_the_project", href: "/about"}
    - {name: "widget_footer_site_links_contact", href: "/about#about-contact"}
  widget_footer_link_section_yang_center:
    - {name: "widget_footer_yang_center_our_values", href: "https://www.birds.cornell.edu/ccb/our-values/", target: "_blank"}
    - {name: "widget_footer_yang_center_research", href: "https://www.birds.cornell.edu/ccb/research/", target: "_blank"}
    - {name: "widget_footer_yang_center_technology", href: "https://www.birds.cornell.edu/ccb/technology/", target: "_blank"}
    - {name: "widget_footer_yang_center_education", href: "https://www.birds.cornell.edu/ccb/education/", target: "_blank"}
    - {name: "widget_footer_yang_center_publications", href: "https://www.birds.cornell.edu/ccb/publications/", target: "_blank"}
  widget_footer_link_section_explore:
    - {name: "widget_footer_explore_more_bird_cams", href: "https://www.allaboutbirds.org/cams/", target: "_blank"}
    - {name: "widget_footer_explore_more_birds_of_the_world", href: "https://birdsoftheworld.org/bow/home", target: "_blank"}
    - {name: "widget_footer_explore_more_ebird_status_and_trends", href: "https://science.ebird.org/status-and-trends", target: "_blank"}
    - {name: "widget_footer_explore_more_our_youtube_videos", href: "https://www.youtube.com/labofornithology", target: "_blank"}
  widget_footer_link_section_learning:
    - {name: "widget_footer_lifelong_learning_online_courses", href: "https://academy.allaboutbirds.org/", target: "_blank"}
    - {name: "widget_footer_lifelong_learning_bird_walks_and_events", href: "https://www.birds.cornell.edu/home/visit/events/", target: "_blank"}
    - {name: "widget_footer_lifelong_learning_spring_field_ornithology", href: "https://academy.allaboutbirds.org/product/spring-field-ornithology-northeast/", target: "_blank"}
    - {name: "widget_footer_lifelong_learning_k12_education", href: "https://www.birds.cornell.edu/k12", target: "_blank"}
  widget_footer_link_section_support:
    - {name: "widget_footer_support_our_cause_join_the_lab", href: "https://join.birds.cornell.edu/page/150611/donate/1?ea.tracking.id=WXXXXX14C", target: "_blank"}
    - {name: "widget_footer_support_our_cause_donate", href: "https://give.birds.cornell.edu/page/132162/donate/1?ea.tracking.id=ENR", target: "_blank"}
    - {name: "widget_footer_support_our_cause_monthly_giving", href: "https://give.birds.cornell.edu/page/99134/donate/1?ea.tracking.id=BCF", target: "_blank"}
    - {name: "widget_footer_support_our_cause_membership_services", href: "https://www.birds.cornell.edu/home/members/", target: "_blank"}
    - {name: "widget_footer_support_our_cause_shop_for_our_cause", href: "https://www.birds.cornell.edu/home/shop-for-our-cause/", target: "_blank"}
  widget_footer_link_section_about:
    - {name: "widget_footer_about_cornell_lab_of_ornithology", href: "http://birds.cornell.edu/", target: "_blank"}
    - {name: "widget_footer_about_web_accessibility_assistance", href: "https://www.birds.cornell.edu/home/web-accessibility-assistance/", target: "_blank"}
    - {name: "widget_footer_about_privacy_policy", href: "https://privacy.cornell.edu/information-use-cornell", target: "_blank"}
    - {name: "widget_footer_about_terms_of_use", href: "https://www.birds.cornell.edu/home/terms-of-use/", target: "_blank"}
COPYRIGHT_HOLDERS: 'Cornell University'
FOOTER_TOP_LOGO: 'yang_logo_white.png'
FOOTER_BOTTOM_LOGOS: ['cornell-logo-white.png']
TEAM_MEMBERS:
  - {name: "Stefan Kahl", role: "about_team_role_project_lead_and_web", img: "stefan.png"}
  - {name: "Felix Günther", role: "about_team_role_backend", img: "felix.png"}
  - {name: "Patrick T. Chaopricha", role: "about_team_role_hardware", img: "patrick.png"}
  - {name: "Max Mauermann", role: "about_team_role_web", img: "max.png"}
  - {name: "Josef Haupt", role: "about_team_role_web", img: "josef.png"}
  - {name: "Isabella Marshall", role: "about_team_role_field_ops", img: "isabella.png"}