PROJECT_ID: 'swamp'
PROJECT_NAME: '099_swamp'
RECORDER_GROUP: 99
SPECIES_DATA: 'swamp'
DEPLOYMENT_LAT: 42.479723
DEPLOYMENT_LON: -76.451566
TIMEZONE: 'America/New_York'
TIME_FORMAT: '12h'
RECORDERS:
  1: {id: '0271', lat: 42.4786, lon: -76.4407, habitat: 'habitat_shrubs_and_trees', img: 'swamp_unit_1.jpg'}
  2: {id: '0829', lat: 42.4768, lon: -76.4396, habitat: 'habitat_shrubs_and_meadow', img: 'swamp_unit_2.jpg'}
  3: {id: '0269', lat: 42.4769, lon: -76.4426, habitat: 'habitat_shrubs_and_meadow', img: 'swamp_unit_3.jpg'}
  4: {id: '0270', lat: 42.4769, lon: -76.4442, habitat: 'habitat_shrubs_and_trees', img: 'swamp_unit_4.jpg'}
  5: {id: '0272', lat: 42.4796, lon: -76.4514, habitat: 'habitat_feeder_garden_and_pond', img: 'swamp_unit_5.jpg'}
  7: {id: '0275', lat: 42.4801, lon: -76.4543, habitat: 'habitat_trees_and_pond', img: 'swamp_unit_7.jpg'}
  8: {id: '0276', lat: 42.4782, lon: -76.4547, habitat: 'habitat_forest', img: 'swamp_unit_8.jpg'}
  9: {id: '0274', lat: 42.4753, lon: -76.4451, habitat: 'habitat_forest_clearing', img: 'swamp_unit_9.jpg'}
  10: {id: '0277', lat: 42.4742, lon: -76.4488, habitat: 'habitat_shrubs_and_pond', img: 'swamp_unit_10.jpg'}
MAP_ZOOM_LEVEL: 15
MAIN_HEADER_IMG_LIST: ['ssw_main_header_1.jpg', 'ssw_main_header_2.jpg']
ABOUT_HEADER_IMG_LIST: ['ssw_about_header_1.jpg', 'ssw_about_header_2.jpg', 'ssw_about_header_3.jpg', 'ssw_about_header_4.jpg', 'ssw_about_header_5.jpg']
LIVE_STREAM_URL: 'https://birdnetlive.duckdns.org/ssw'
DONATION_URL: 'https://give.birds.cornell.edu/page/132162/donate/1?ea.tracking.id=ENR'
PROJECT_ACRONYM: 'SWAMP'
PROJECT_SUBTITLE: 'AI-powered acoustic monitoring'
PROJECT_SUBTITLE_DESC: 'We listen to the sounds of the animals in Sapsucker Woods and track species diversity over large spatio-temporal scales.'
PROJECT_GOAL: 'The Sapsucker Woods Acoustic Monitoring Project combines technology and community engagement to showcase the power of acoustic monitoring in understanding the natural world. By listening to the sounds of Sapsucker Woods, visitors can explore how advanced tools are used to study wildlife and gain a deeper appreciation for the diversity of birdlife in the area.'
PRIMARY_COLOR: '#b31b1b'
SECONDARY_COLOR: '#2e261f'
PLOT_PRIMARY_COLOR: '#385B75'
BUTTON_COLOR: '#36824b'
FAVICON: 'swamp_favicon.ico'
PAGE_TITLE: 'SWAMP'
LOGO_MOBILE: 'clo_swamp_short_mobile_horizontal_color.png'
LOGO_DESKTOP: 'clo_swamp_short_horizontal_color.png'
LEARN_MORE_BASE_URL: 'https://www.allaboutbirds.org/guide/'
FOOTER_LINKS:
  Site Links:
    - {name: "Home", href: "/"}
    - {name: "Detections", href: "/detections"}
    - {name: "Recording units", href: "/recorder/1"}
    - {name: "About the project", href: "/about"}
    - {name: "Contact", href: "/about#about-contact"}
  Yang Center:
    - {name: "Our values", href: "https://www.birds.cornell.edu/ccb/our-values/", target: "_blank"}
    - {name: "Research", href: "https://www.birds.cornell.edu/ccb/research/", target: "_blank"}
    - {name: "Technology", href: "https://www.birds.cornell.edu/ccb/technology/", target: "_blank"}
    - {name: "Education", href: "https://www.birds.cornell.edu/ccb/education/", target: "_blank"}
    - {name: "Publications", href: "https://www.birds.cornell.edu/ccb/publications/", target: "_blank"}
  Explore More:
    - {name: "Bird Cams", href: "https://www.allaboutbirds.org/cams/", target: "_blank"}
    - {name: "Birds of the World", href: "https://birdsoftheworld.org/bow/home", target: "_blank"}
    - {name: "eBird Status and Trends", href: "https://science.ebird.org/status-and-trends", target: "_blank"}
    - {name: "Our Youtube Videos", href: "https://www.youtube.com/labofornithology", target: "_blank"}
  Lifelong Learning:
    - {name: "Online Courses", href: "https://academy.allaboutbirds.org/", target: "_blank"}
    - {name: "Bird Walks & Events", href: "https://www.birds.cornell.edu/home/visit/events/", target: "_blank"}
    - {name: "Spring Field Ornithology", href: "https://academy.allaboutbirds.org/product/spring-field-ornithology-northeast/", target: "_blank"}
    - {name: "K–12 Education", href: "https://www.birds.cornell.edu/k12", target: "_blank"}
  Support Our Cause:
    - {name: "Join the Lab", href: "https://join.birds.cornell.edu/page/150611/donate/1?ea.tracking.id=WXXXXX14C", target: "_blank"}
    - {name: "Donate", href: "https://give.birds.cornell.edu/page/132162/donate/1?ea.tracking.id=ENR", target: "_blank"}
    - {name: "Monthly Giving", href: "https://give.birds.cornell.edu/page/99134/donate/1?ea.tracking.id=BCF", target: "_blank"}
    - {name: "Membership Services", href: "https://www.birds.cornell.edu/home/members/", target: "_blank"}
    - {name: "Shop for Our Cause", href: "https://www.birds.cornell.edu/home/shop-for-our-cause/", target: "_blank"}
  About:
    - {name: "Cornell Lab of Ornithology", href: "http://birds.cornell.edu/", target: "_blank"}
    - {name: "Web Accessibility Assistance", href: "https://www.birds.cornell.edu/home/web-accessibility-assistance/", target: "_blank"}
    - {name: "Privacy Policy", href: "https://privacy.cornell.edu/information-use-cornell", target: "_blank"}
    - {name: "Terms of Use", href: "https://www.birds.cornell.edu/home/terms-of-use/", target: "_blank"}
COPYRIGHT_HOLDERS: 'Cornell University'
FOOTER_TOP_LOGO: 'yang_logo_white.png'
FOOTER_BOTTOM_LOGOS: ['cornell-logo-white.png']
TEAM_MEMBERS:
  - {name: "Stefan Kahl", role: "about_team_role_project_lead_and_web", img: "stefan.png"}
  - {name: "Felix Günther", role: "about_team_role_backend", img: "felix.png"}
  - {name: "Patrick T. Chaopricha", role: "about_team_role_hardware", img: "patrick.png"}
  - {name: "Max Mauermann", role: "about_team_role_web", img: "max.png"}
  - {name: "Josef Haupt", role: "about_team_role_web", img: "josef.png"}
  - {name: "Isabella Marshall", role: "about_team_role_field_ops", img: "isabella.png"}